### PR TITLE
Upgrade to Quarkus 3.23.0

### PR DESCRIPTION
**Pull request by gsmet**
Make sure that you have run `./mvnw -Dsync` and included the changes in your pull request (preferably in the same commit, unless it makes sense to do otherwise).

Thanks!

### CODE REVIEW

**Comment by metacosm** [comment]
Might be a flake as 7.1.2 should build with 3.23, even though it's probably not the best configuration.

**Comment by gsmet** [comment]
@metacosm doesn't look like a flake:

```
2025-05-22T20:40:01.5081282Z Caused by: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: io/fabric8/kubernetes/client/server/mock/KubernetesServer
2025-05-22T20:40:01.5082079Z 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
2025-05-22T20:40:01.5082972Z 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
2025-05-22T20:40:01.5083598Z 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
2025-05-22T20:40:01.5084215Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2025-05-22T20:40:01.5084815Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2025-05-22T20:40:01.5085279Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2025-05-22T20:40:01.5085871Z Caused by: java.lang.NoClassDefFoundError: io/fabric8/kubernetes/client/server/mock/KubernetesServer
2025-05-22T20:40:01.5086673Z 	at io.quarkiverse.operatorsdk.it.CustomKubernetesServerTestResource.configureServer(CustomKubernetesServerTestResource.java:11)
2025-05-22T20:40:01.5087571Z 	at io.quarkus.test.kubernetes.client.AbstractKubernetesTestResource.start(AbstractKubernetesTestResource.java:30)
2025-05-22T20:40:01.5088312Z 	at io.quarkus.test.common.TestResourceManager$TestResourceRunnable.run(TestResourceManager.java:674)
2025-05-22T20:40:01.5088953Z 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
2025-05-22T20:40:01.5089460Z 	... 3 more
2025-05-22T20:40:01.5089874Z Caused by: java.lang.ClassNotFoundException: io.fabric8.kubernetes.client.server.mock.KubernetesServer
2025-05-22T20:40:01.5090515Z 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
2025-05-22T20:40:01.5091125Z 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
2025-05-22T20:40:01.5091631Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
2025-05-22T20:40:01.5092169Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:576)
2025-05-22T20:40:01.5093027Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:523)
2025-05-22T20:40:01.5093683Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:576)
2025-05-22T20:40:01.5094472Z 	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:523)
2025-05-22T20:40:01.5095011Z 	... 7 more
```

**Comment by loicmathieu** [comment]
@gsmet there is an issue in the latest Google Cloud cloud-sdk image, I modify the develop branch of the extension to use an old version.
I plan to do a release soon, it should fix the issue.

**Comment by loicmathieu** [comment]
In fact the issue on the Google cloud-sdk image is fixed so the latest tag should not resolves to an image that works.

**Comment by metacosm** [comment]
https://github.com/quarkiverse/quarkus-operator-sdk/pull/1101 shows that this upgrade should work so I'm not sure why the platform tests are failing.
